name: Release Resume
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Get the latest release
        id: get_latest_release
        run: |
          LATEST_RELEASE=$(curl -s \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/YanishR/YanishR/releases/latest)

          RELEASE_ID=$(echo "$LATEST_RELEASE" | jq -r .id)

          echo "RELEASE_ID=$RELEASE_ID" >> $GITHUB_ENV

      - name: Delete the latest release
        run: |
          curl -s -X DELETE \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/YanishR/YanishR/releases/${{ env.RELEASE_ID }}

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: resume
          root_file: Yanish_Rambocus_Resume.tex

      - name: Date
        id: date 
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY_MM_DD"

      - name: Create Dummy Release
        uses: xresloader/upload-to-github-release@v1
        with:
          file: "resume/Yanish_Rambocus_Resume.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
          default_release_name: Dummy Release
          tag_name: dummy
              
      - name: Delete Release
        run: |
          curl -X GET --location "https://api.github.com/repos/YanishR/YanishR/releases/latest" \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"tag_name":"'"$VERSION"'","target_commitish":"main","name":"Resume","draft":false,"prerelease":false,"generate_release_notes":true}'
      - name: Delete All but Dummy Release Pt2
        uses: sgpublic/delete-release-action@v1.1
        with:
          release-drop: true
          release-keep-count: -1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release 
        uses: xresloader/upload-to-github-release@v1
        with:
          file: "resume/Yanish_Rambocus_Resume.pdf"
          overwrite: true
          token: ${{ secrets.GITHUB_TOKEN }}
          default_release_name: Resume 
          tag_name: ${{ steps.date.outputs.day }}-${{ steps.date.outputs.month}}-${{ steps.date.outputs.year }}
          update_latest_release: true
          draft: false
          update_release_body: |
              Please find my resume available for download below. 
              _Note: *.tar.gz and *.zip files are automatically uploaded for Github Releases, they are not needed to view the resume._
      - name: Delete all but Resume Release 
        uses: sgpublic/delete-release-action@v1.1
        with:
          release-drop: true
          release-keep-count: -1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
