name: Release Resume
on: 
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: resume
          root_file: Yanish_Rambocus_Resume.tex

      - name: Create release 
        uses: xresloader/upload-to-github-release@v1
        with:
          file: "resume/Yanish_Rambocus_Resume.pdf"
          overwrite: true
          token: ${{ secrets.GITHUB_TOKEN }}
          default_release_name: Resume
          tag_name: main
          update_latest_release: true
          draft: false
          update_release_body: |
              Please find my Resume available for download below. 
              _Note: *.tar.gz and *.zip files are automatically uploaded for Github Releases, they are not needed to view the resume._

